### ISSUE TITLE
configure co-authors locally (by default)

### ISSUE THREAD

**Issue by otlin100** [hekmekk/git-team#10]
# Feature Request

Write co-authors in local config and not in global 

#### current behaviour

global config is written

#### desired behaviour

write in local config

## use case / why is this important?

Oftentimes I forget to use 'git team disable'. If you push private projects without viewing the commit in the editor, the co-authors names and emails may appear on unwanted locations.

**Comment by hekmekk** [comment]
Hello and thanks for your feature request. In order to make this a backwards compatible change, I'm currently in favor of introducing a config option that lets you choose between `global` and `repo-local` co-author activation status. This would still keep your co-author assignments within the global git config but have an activation state depending on the repository you're currently in.

**Comment by hekmekk** [comment]
FYI: started working on it in this [feature branch](https://github.com/hekmekk/git-team/tree/configurable-activation-scope)

**Comment by hekmekk** [comment]
The necessary adjustments have been integrated into master. If you don't mind building git-team yourself, you may already checkout the feature @otlin100 . A release will be available soon though.

**Comment by hekmekk** [comment]
Has been implemented in release v1.4.0.
