### ISSUE TITLE
brew formula needs style fix

### ISSUE THREAD

**Issue by delitescere** [hekmekk/git-team#14]
```sh
$ brew info git-team

Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the hekmekk/git-team tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/hekmekk/homebrew-git-team/Formula/git-team.rb:11

hekmekk/git-team/git-team: stable 1.5.3, HEAD
Manage and enhance `git commit` messages with co-authors
https://github.com/hekmekk/git-team
/usr/local/Cellar/git-team/1.5.3 (7 files, 4.7MB) *
  Built from source on 2021-04-20 at 15:46:22
From: https://github.com/hekmekk/homebrew-git-team/blob/HEAD/Formula/git-team.rb
==> Dependencies
Build: go ✔
==> Options
--HEAD
	Install HEAD version
```

The use of `cellar` in the `Taps/hekmekk/homebrew-git-team/Formula/git-team.rb` is causing the warning:

```rb
  bottle do
    cellar :any_skip_relocation
  end
```

**Comment by hekmekk** [comment]
Thanks for submitting the issue :bouquet:  Will get onto it asap.

**Comment by hekmekk** [comment]
If I understood homebrew bottles correctly – they are builts from homebrew maintainers –, this section is not required by `git-team`, and has therefore been removed. The style warning should have disappeared accordingly.

**Comment by hekmekk** [comment]
Hey, thanks again for bringing this up.

The reason `/usr/local/etc/git-team` needs to be removed explicitly is because the homebrew formula uses a hardcoded path instead of relying on the configurable `etc` path variable. As git-team relies on that fixed hooks path, I need to make git-team lookup the hooks path dynamically so I can use the special homebrew variables.

I'm afraid I do not get the `git-lfs` issue though :thinking: Could you elaborate on that, please?
